In [5]:
import numpy as np
# Numerical python
# n-dim Array

In [6]:
np1 = np.array([1,2,3,4])
np1

array([1, 2, 3, 4])

In [7]:
#Range 
np1 = np.arange(5)
np1

array([0, 1, 2, 3, 4])

In [8]:
#Step
np1 = np.arange(1,6,2)
np1

array([1, 3, 5])

In [9]:
#Zeroes
np1 = np.zeros(5)
np1

array([0., 0., 0., 0., 0.])

In [10]:
np1 = np.zeros((2,2))
np1

array([[0., 0.],
       [0., 0.]])

In [11]:
#ones
np1 = np.ones(5)
np1

array([1., 1., 1., 1., 1.])

In [12]:
np1 = np.ones((2,3))
np1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [13]:
print(np1.shape) #rows and column
print(np1.dtype) # Data type
print(np1.ndim) # Dimention
print(np1.size) # Byte 1 byte = 8 bits 
print(np1.itemsize) # total no elements

(2, 3)
float64
2
6
8


In [14]:
# Index
print(np1)
print(np1[0][0])

[[1. 1. 1.]
 [1. 1. 1.]]
1.0


In [15]:
# List Vs Tuple
L = [1,2,3]
A = np.array([1,2,3])

print(L[0])
print(A[0])

1
1


In [16]:
print(L * 2)
print(A * 2)

[1, 2, 3, 1, 2, 3]
[2 4 6]


In [17]:
print(L + [3,2,1])
print(A + [3,2,1])

[1, 2, 3, 3, 2, 1]
[4 4 4]


Dot Product

In [19]:
l1 = np.array([1,2,3])
l2 = np.array([2,4,6])


In [20]:
np.dot(l1,l2)

28

In [21]:
mul = l1 * l2
mul

array([ 2,  8, 18])

In [22]:
np.sum(mul)

28

In [23]:
l1 @ l2

28

In [24]:
(l1 * l2).sum()

28

N Dim

In [56]:
np1 = np.array([[1,2,3],[5,7,9],[3,6,4],[3,4,5],[9,8,7]])
np1

array([[1, 2, 3],
       [5, 7, 9],
       [3, 6, 4],
       [3, 4, 5],
       [9, 8, 7]])

In [78]:
np1.shape

(5, 3)

In [58]:
np1[0]

array([1, 2, 3])

In [60]:
np1[0][0]

1

In [64]:
np1[0:2]

array([[1, 2, 3],
       [5, 7, 9]])

In [66]:
np1[1:4]

array([[5, 7, 9],
       [3, 6, 4],
       [3, 4, 5]])

In [74]:
np1[1:4,0]

array([5, 3, 3])

In [76]:
np1[1:4,0:2]

array([[5, 7],
       [3, 6],
       [3, 4]])

In [82]:
np1

array([[1, 2, 3],
       [5, 7, 9],
       [3, 6, 4],
       [3, 4, 5],
       [9, 8, 7]])

In [84]:
np1[1,1]

7

In [100]:
np1[0:3]

array([[1, 2, 3],
       [5, 7, 9],
       [3, 6, 4]])

In [108]:
np1[0:3][0]

array([1, 2, 3])

In [110]:
np1[0:3][0][0]

1

In [114]:
np1[0:3,1]

array([2, 7, 6])

Bool index

In [119]:
BoolIdx = np1[0:3] > 5
BoolIdx

array([[False, False, False],
       [False,  True,  True],
       [False,  True, False]])

In [123]:
np1[0:3][BoolIdx]

array([7, 9, 6])

In [125]:
np1

array([[1, 2, 3],
       [5, 7, 9],
       [3, 6, 4],
       [3, 4, 5],
       [9, 8, 7]])

In [129]:
np1[np1 > 5]

array([7, 9, 6, 9, 8, 7])

In [133]:
np.where(np1 > 5 , np1 , 0)  # np.where(condition , true, false)

array([[0, 0, 0],
       [0, 7, 9],
       [0, 6, 0],
       [0, 0, 0],
       [9, 8, 7]])

Multiple index

In [203]:
np1 = np.array([1,4,65,9,7,4,2,45,56])
np1

array([ 1,  4, 65,  9,  7,  4,  2, 45, 56])

In [205]:
idxs = [0,3,5,6]
idxs

[0, 3, 5, 6]

In [207]:
np1[idxs]

array([1, 9, 4, 2])

In [209]:
np.argwhere(np1 > 5)  # only returns the index

array([[2],
       [3],
       [4],
       [7],
       [8]], dtype=int64)

In [211]:
np.argwhere(np1 > 5).flatten()

array([2, 3, 4, 7, 8], dtype=int64)

In [213]:
np.where(np1 > 5)

(array([2, 3, 4, 7, 8], dtype=int64),)