In [38]:
import numpy as np

# Array attributes

In [40]:
n = np.array([[1., 0., 0.],[0., 1., 2.]])
n

array([[1., 0., 0.],
       [0., 1., 2.]])

In [41]:
n.shape

(2, 3)

In [42]:
n.ndim

2

In [43]:
n.dtype

dtype('float64')

In [44]:
n.dtype.name

'float64'

In [45]:
n.size

6

In [46]:
n.itemsize

8

In [47]:
n.data

# Array Creation

### Python sequence to Np

In [50]:
list = [1,2,3,4]
tuple = (1,2,3,4)

In [51]:
np.array(list)

array([1, 2, 3, 4])

In [52]:
np.array(tuple)

array([1, 2, 3, 4])

### 1 D

#### arange(start, stop, step)

In [55]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [56]:
np.arange(2,5)

array([2, 3, 4])

In [57]:
np.arange(3,10,3)

array([3, 6, 9])

In [58]:
np.arange(5,dtype=np.float16)

array([0., 1., 2., 3., 4.], dtype=float16)

### 2D

#### np.eye(n, m)

In [61]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
np.eye(2,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

# ndarray 

In [91]:
np.zeros(3)

array([0., 0., 0.])

In [93]:
np.zeros([3,3])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [95]:
np.ones(4)

array([1., 1., 1., 1.])

In [97]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])